### ISSUE TITLE
Unexpectedly found nil while unwrapping an Optional value

### ISSUE THREAD

**Issue by ThisIsYuu** [ThisIsYuu/CrashyPlane#3]
Bug exist in GameScene.swift

**Comment by JZDesign** [comment]
I can fix that quick if you'll allow me to contribute.

**Comment by ThisIsYuu** [comment]
@JZDesign  Yeah sure, send a pull request as soon as you are done . Thank You.

**Comment by JZDesign** [comment]
@JZDesign I'm unable to push my branch up. Do I need to be marked a as a contributor on your repo first?

**Comment by ThisIsYuu** [comment]
@JZDesign You need to fork this repo first. Then add changes to your repo and then push them into mine.

**Comment by ThisIsYuu** [comment]
@JZDesign Thank You🙂
